#服务端口
server:
  port: 8160
#服务名
spring:
  application:
    name: service-user

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root


  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  #环境设置：dev、test、prod
  profiles:
    active: dev

  #nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #redis 配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
#mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/tianle/userservice/mapper/xml/*.xml

wx:
  open:
    app_id: your appid
    app_secret: your app_secret
    redirect_url: your redirect_url