#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  #nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t6UD93127xNfXfyTGpF
      keysecret: RCeHCLV9PqB9LbbdpdwZw6LuJ2iY3Q
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-tianle



